name: yafe
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_intent: 0.2.1
  carousel_slider:
  cached_network_image: ^1.1.1
  chewie:
  cloud_firestore: 0.8.2+3
  cupertino_icons: ^0.1.2
  file_picker:
  firebase_storage: 1.0.4
  flutter_pollfish: ^0.2.1
  flutter_speed_dial:
  flutter_swiper:
  flutter_twitter_login:

  flutter_webview_plugin:

  image_picker: 0.4.12+1
  intl:
  path_provider:
  rxdart:
  share: 0.5.3
  sentry:
  shared_preferences: 0.4.3
  twitter:
  url_launcher: 4.1.0+1
  video_player: 0.9.0
  webview_flutter: 0.2.0
  yaml:

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: 0.2.5+1
  firebase_analytics: 1.1.0
  firebase_auth: 0.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/hatespeech/
    - config.yaml

  fonts:
    - family: Futura
      fonts:
        - asset: assets/fonts/futuraLight.ttf
          weight: 300
        - asset: assets/fonts/futuraMedium.ttf
          weight: 500
        - asset: assets/fonts/futuraHeavy.ttf
          weight: 700
    - family: Arial
      fonts:
        - asset: assets/fonts/ArialMT.ttf
          weight: 400
